jdbc:
  dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
  url: jdbc:mysql://192.168.246.3:3306/SIMPLE_AUTHORITY
  useUnicode: true
  charaterEncoding: utf8
  databaseName: SIMPLE_AUTHORITY
  serverName: 192.168.246.3
  username: root
  password: 123
  cachePrepStmts: true
  prepStmtsSize: 250
  prepStmtsCacheSqlLimit: 2048
  userServerPrepStmts: true
my: 
  config:
    value: application.yml--------------
server:
  port: 8081
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
  application:
    name: BookPub Catalog Application
  boot:
    admin:
      url: http://192.168.246.3:8090
shell:
  ssh:
    port: 2212
    enabled: true
  auth:
    simple:
      user:
        name: user
        password: 123
info:
  build:
    name: ${project.name}
    description: ${cucumber.version}
    version: ${project.version}
logging:
  path: ./logs
  file: authority.log
  level:
    org.springframework.transaction: TRACE
    com.ibatis: DEBUG