INSERT INTO author (id, first_name, last_name) VALUES (1, 'Alex','Antonov')
INSERT INTO publisher (id, name) VALUES (1, 'Packt')
INSERT INTO book (isbn, title, author_id, publisher_id) VALUES ('978-1-78528-415-1', 'Spring Boot Recipes', 1, 1)
INSERT INTO author (id, first_name, last_name) VALUES (3, 'William','Shakespeare')
INSERT INTO publisher (id, name) VALUES (2, 'Classical Books')
INSERT INTO book (isbn, title, author_id, publisher_id) VALUES ('978-1-23456-789-1', 'Romeo and Juliet', 3, 2)
INSERT INTO author (id, first_name, last_name) VALUES (2, 'Greg','Turnquist')
INSERT INTO book (isbn, title, author_id, publisher_id) VALUES ('978-1-78439-302-1', 'Learning Spring Boot', 2, 1)